name: animated_location_indicator
description: A simple yet customizable plugin for Flutter Map to display the current user location, accuracy and orientation along with automatically animating changes of these properties.
version: 1.0.0
repository: https://github.com/OPENER-next/animated_location_indicator
issue_tracker: https://github.com/OPENER-next/animated_location_indicator/issues

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^1.0.0
  geolocator: ^8.2.0
  latlong2: ^0.8.1
  motion_sensors: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1